### ISSUE TITLE
git causing illegal instruction error on ubuntu 24.04

### ISSUE THREAD

**Issue by Haui1112** [DC-DeepComputing/DC-ROMA_Pad_II_RV-P1B#4]
Hello there,
I've started to build apps but I'm running into kernel errors while fetching git repositories.

## Observed behavior
Git clone fails with ```fatal: fetch-pack: invalid index-pack``` on larger repositories
journalctl logs the following:
```
Oct 29 11:24:00 haui-romapad kernel: CPU: 0 PID: 3228 Comm: git Not tainted 6.6.36 #1
Oct 29 11:24:00 haui-romapad kernel: Hardware name: spacemit k1-x kx107 board (DT)
Oct 29 11:24:00 haui-romapad kernel: epc : 0000003fa46d6958 ra : 0000003fa46d2006 sp : 0000003ff3d35220
Oct 29 11:24:00 haui-romapad kernel:  gp : 0000002ae47c4fe8 tp : 0000003fa4549780 t0 : 000000006e612072
Oct 29 11:24:00 haui-romapad kernel:  t1 : 0000002ae4886780 t2 : 0000000000000010 s0 : 0000003ff3d35270
Oct 29 11:24:00 haui-romapad kernel:  s1 : 0000002ae48740d4 a0 : 000000000000042f a1 : 0000000000000060
Oct 29 11:24:00 haui-romapad kernel:  a2 : 0000000000000008 a3 : 0000000000000100 a4 : 0000002ae488cab4
Oct 29 11:24:00 haui-romapad kernel:  a5 : 0000000000000020 a6 : 00000000000046e1 a7 : 000000000000fff1
Oct 29 11:24:00 haui-romapad kernel:  s2 : 0000000000002b2f s3 : 0000003fa477ad08 s4 : 00000000000046e1
Oct 29 11:24:00 haui-romapad kernel:  s5 : 0000000000008dbc s6 : 0000003ff3d35430 s7 : 0000000000002b2f
Oct 29 11:24:00 haui-romapad kernel:  s8 : 000000000000444c s9 : 0000003fa46e4008 s10: 0000000000001000
Oct 29 11:24:00 haui-romapad kernel:  s11: 0000002ae4874483 t3 : 0000002ae488a334 t4 : 0000002ae4886780
Oct 29 11:24:00 haui-romapad kernel:  t5 : 0000000000008000 t6 : 0000000000001a71
Oct 29 11:24:00 haui-romapad kernel: status: 8000000200004620 badaddr: 00000000d30c2e57 cause: 0000000000000002
```

## Expected behavior
The git clone or fetch succeeds.

## Steps to reproduce
1. install git
2. git fetch https://github.com/dart-lang/sdk.git
3. observe error

**Comment by wmat** [comment]
No problem here:

wmat@romapad:~$ git clone https://github.com/dart-lang/sdk.git
Cloning into 'sdk'...
remote: Enumerating objects: 1598268, done.
remote: Counting objects: 100% (12549/12549), done.
remote: Compressing objects: 100% (4054/4054), done.
remote: Total 1598268 (delta 8309), reused 12367 (delta 8185), pack-reused 1585719 (from 1)
Receiving objects: 100% (1598268/1598268), 1.38 GiB | 5.62 MiB/s, done.
Resolving deltas: 100% (1271251/1271251), done.
Updating files: 100% (50118/50118), done.

**Comment by Haui1112** [comment]
interesting. did you unminimize and/or update your system and did you change the bianbu.sources.1 list as mentioned in issue #1 ?

As of now I assume this is an issue of the original (not updated, minimized) version of ubuntu on the PAD or even the version that gets installed from the recovery image.

**Comment by wmat** [comment]
Yes, I unminimized and updated.  Unminimizing changes the sources to canonicals servers.

**Comment by Haui1112** [comment]
Okay, I can confirm now.

```
sudo unminimize
```

Solves the issue. I have not done an additional upgrade since the mesa drivers are affected by that one but the initial issue is now solved. Closing this issue.
